version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
  db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/foo
      - shared-stuff:/stuff

volumes:
  db-data:
  shared-stuff: